### ISSUE TITLE
Ordenação dos dados utilizando banco em Memória vs IndexedDB

### ISSUE THREAD

**Issue by guiebitt** [jpwerka/web-backend-api#11]
Olá,

Existe uma diferença de comportamento/gravação em relação a utilizar os dados em memória vs indexedDB.

Quando memória, os dados são gravados ordenados conforme inclusão, ou seja, um item novo sempre fica no final;
Quando indexedDB, os dados são gravados ordenados pelo ID;

Seria possível configurar o comportamento para ordenação sempre via ID ou sempre baseado na ordem de gravação independente do tipo do banco?

**Comment by jpwerka** [comment]
Ajustado para ter o mesmo comportamento no array em memória, ordenando pelo `data.id` da mesma forma que o IndexDB.
Favor atualizar a para versão **"0.0.23"**
